version: "3.8"

services:
    #ngnix:
    #    depends_on:
    #        - lnchecker
    #    image: nginx:latest
    #    volumes:
    #        - ./nginx.conf:/etc/nginx/conf.d/default.conf
    #    network_mode: "host"
    #    restart: on-failure
    lnchecker:
        build: .
        ports: 
          - 80:8080
        network_mode: "host"
        restart: on-failure